language: bash

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install espeak
    - sudo apt-get install notify-osd

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.1.3.tgz" | tar zx

script:
    - bash testtimer 
