#!/bin/bash

leftt=`ps -eo '%t %c' | grep simpletimer | grep -oh '[0-9][0-9]:[0-9][0-9]' | awk -F: '{print $1*60+$2}'`
killall simpletimer
source ~/.timervariables
if ps -C seetimer > /dev/null ; then
	killall seetimer
fi
leftt=$(($stimes-$leftt))
echo 'export stimes='$leftt > ~/.timervariables
echo 'export leftt='$leftt >> ~/.timervariables
