#! /bin/bash
#file: testtimer
#Simple test for the pausetime and restarttimer. Test if the runtime within one second
# of sum of the timer and the pause. 


setUp()
{
	timetest=7 ; pausetime=5; total=$((timetest+pausetime))
}

testTime()
{
	start=`date +%s` 
	. simpletimer $timetest's' &
	sleep $pausetime's' ; . pausetimer ; sleep $pausetime's'; . restarttimer 
	end=`date +%s`
	runtime=$((end-start))
assertTrue '[ $runtime -ge $((total-1)) ] && [ $runtime -le $((total+1)) ]'
}

# load shunit2
. shunit2-2.1.3/src/shell/shunit2
