#! /bin/bash
#file: testtimer


setUp()
{
	timetest=7 ; pausetime=5; total=$((timetest+pausetime))
}

testTime()
{
	start=`date +%s` 
	simpletimer $timetest's' &
	sleep $pausetime's' ; pausetimer ; sleep $pausetime's'; restarttimer 
	end=`date +%s`
	runtime=$((end-start))
assertTrue '[ $runtime -ge $((total-1)) ] && [ $runtime -le $((total+1)) ]'
}

# load shunit2
. /usr/bin/shunit2
